### PR TITLE
Please push new changes out to /release :)

### LINKED ISSUE #23: Errors in CDN jsDelivr minified version
Just saw that in the latest CDN jsDelivr version (1.0.3) : all `className` properties are replaced with `class`, and I think it throws error in IE8.

### PR DESCRIPTION
**Pull request by tomByrer**
Will fix #23

### CODE REVIEW

**Comment by RobertoGonzalez** [comment]
Thanks @tomByrer ! It seems we somehow missed that release.

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
Pull request closed?

**Comment by tomByrer** [comment]
Thanks Roberto, [updated on jsDelivr CDN](http://www.jsdelivr.com/#!jquery.midnight)

> It seems we somehow missed that release

Is Midnight when you work on this?  (joking) ;)

**Comment by RobertoGonzalez** [comment]
@tomByrer Awesome!

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
What is awsome?

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
Sry if iam a little bit after in the diskution.

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
Who are my co-workers if i have some?

**Pull request merged**
